name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.4.0
  flutter:
    sdk: flutter
  very_good_analysis: 6.0.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:

    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/